# Generated by Django 4.2 on 2025-06-11 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("token", models.CharField(max_length=255)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_command", models.TextField(blank=True, null=True)),
                ("command_id", models.UUIDField(blank=True, null=True)),
                ("last_output", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
