# Generated by Django 4.2 on 2025-06-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_cmd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_seen",
            field=models.DateTimeField(),
        ),
    ]
