# Generated by Django 5.2.3 on 2025-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_cmd", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="created_at",
        ),
        migrations.AddField(
            model_name="client",
            name="last_command",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
