# Generated by Django 5.2.3 on 2025-06-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_cmd", "0002_remove_client_created_at_client_last_command_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="command_processed",
            field=models.BooleanField(default=False),
        ),
    ]
