# Generated by Django 5.2.3 on 2025-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_cmd", "0003_client_command_processed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="command_processed",
        ),
        migrations.AddField(
            model_name="client",
            name="command_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
