# Generated by Django 5.2.3 on 2025-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote_cmd", "0004_remove_client_command_processed_client_command_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
